name: nike_redesign
description: "An application for Nike Mobile Apps."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  palette_generator: ^0.3.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/common/assets/images/
    - lib/common/assets/fonts/
    - lib/common/assets/jsons/
  fonts:
    - family: HelveticaNow
      fonts:
        - asset: lib/common/assets/fonts/HelveticaNowText-Regular.ttf
        - asset: lib/common/assets/fonts/HelveticaNowText-Medium.ttf
          weight: 500
        - asset: lib/common/assets/fonts/HelveticaNowText-Bold.ttf
          weight: 700
        - asset: lib/common/assets/fonts/HelveticaNowText-Black.ttf
          weight: 900
